#!/usr/bin/env python2
import sys, os, time, subprocess
from pdb import set_trace


configs = {}
inf = open('ttbarxsec.cfg')
data = inf.read()
data = data.split('\n')
for l in data:
	l = l.split('#')[0]
	if '=' in l:
		name = l.split('=')[0].strip()
		val = l.split('=')[1].strip()
		configs[name] = val

print configs

swdir = os.path.realpath(os.environ['URA_PROJECT'])
jobid = os.environ['jobid']
inputdir = os.path.join(swdir, 'inputs')
inputdir = os.path.join(inputdir, jobid)

jobdir = sys.argv[1]
exe = sys.argv[2]
execonfig = sys.argv[3]
jobargs = sys.argv[4:]

#os.system('git commit -a -m ' + jobdir)

#os.mkdir('Production_'+ time.strftime("%Y-%m-%d_%H:%M:%S", time.gmtime()))
if os.path.isdir(jobdir):
	print jobdir, 'exists: EXIT'
	sys.exit(-1)
jobdir = os.path.join(os.getcwd(), jobdir)
os.mkdir(jobdir)

os.system('cp ' + execonfig + ' ' + jobdir)
execonfig = os.path.join(jobdir, os.path.basename(execonfig))

p = subprocess.Popen(['which', exe], stdout=subprocess.PIPE)
exe = p.stdout.read().split('\n')[0]
cpcomm = 'cp ' + exe + ' ' + jobdir
os.system(cpcomm)
exe = os.path.join(jobdir, os.path.basename(exe))
#print exe, execonfig

p = subprocess.Popen(['ldd', exe], stdout=subprocess.PIPE)
slibs = p.stdout.read().split('\n')
slibs = [(l.split('=>')[-1].split('(')[0]).strip() for l in slibs if 'uscms' in l]
libs = []
for lib in slibs:
    cpcomm = 'cp ' + lib + ' ' + jobdir
    os.system(cpcomm)
    libs.append(os.path.join(jobdir, os.path.basename(lib)))


files = os.listdir(inputdir)

samplefiles = [f for f in files if 'txt' in f]

transferdir = os.path.join(inputdir, 'INPUT')
transferfiles = []
if os.path.isdir(transferdir):
	transferfiles = os.listdir(transferdir)

transferfiles = [os.path.join(transferdir, tf) for tf in transferfiles]
transferfiles.append(execonfig)

transferfiles += libs
transferfiles += [exe]
transferfiles += [execonfig]

transferfiles_config = ', '.join(transferfiles)
print transferfiles_config

for sf in samplefiles:
	if 'QCD' in sf or 'DYJet' in sf or 'WJet' in sf:
		filesperjob = 160
	elif 'DATA' in sf:
		filesperjob = 200
	elif 'Hpp' in sf:
		filesperjob = 40
	elif 'tt_' in sf:
		if configs['PDFTEST'] == '1' and 'tt_PowhegP8' in sf:
			filesperjob = 20
		else:
			filesperjob = 20
	else:
		filesperjob = 60

	#infile = os.path.join(inputdir, sf)
	jobpath = os.path.join(jobdir, sf.split('.txt')[0])
	os.mkdir(jobpath)
	infile = os.path.join(jobpath, sf)
	print 'cp ' + os.path.join(inputdir, sf) + ' ' + infile
	os.system('cp ' + os.path.join(inputdir, sf) + ' ' + infile)
	infiledes = open(infile, 'r')
	numrootfiles = infiledes.read().count('.root')
	infiledes.close()
	numjobs = max(numrootfiles/filesperjob, 1)
	sample = sf.split('.txt')[0]
	print sf, numjobs
	for j in range(0, numjobs):
		condorfile ="""universe = vanilla
Executable = batch_job.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = {5}
Output = con_{2}.stdout
Error = con_{2}.stderr
Arguments = {0} {1} {6}_out_{2}.root --thread 1 --j {2} --J {3} {4}
Queue

		""".format(os.path.basename(exe), os.path.basename(infile), j, numjobs, ' '.join(jobargs), transferfiles_config+', '+infile, sample)
        
		conf = open(os.path.join(jobpath, 'condor_'+str(j)+'.jdl'), 'w')
		conf.write(condorfile)
		conf.close()

	batch_job="""#!/bin/bash
WORKINGDIR=$PWD
echo $HOSTNAME
echo $WORKINGDIR
EXE=$1
ls -lht

export SCRAM_ARCH={0}
source /cvmfs/cms.cern.ch/cmsset_default.sh
which scram
scram p CMSSW {1}
cd {1}
eval `scramv1 runtime -sh`
cd $WORKINGDIR

export LD_LIBRARY_PATH={2}:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH
echo $LD_LIBRARY_PATH
ldd $EXE

PA=$@
PA=${{PA#* }}

pwd
ls -lht

echo $EXE
echo $PA

./$EXE $PA 

	""".format(os.environ['SCRAM_ARCH'], os.environ['CMSSW_VERSION'], os.environ['LD_LIBRARY_PATH'])

	conf = open(os.path.join(jobpath, 'batch_job.sh'), 'w')
	conf.write(batch_job)
	conf.close()
        
	for j in range(0, numjobs):
		subcommand = 'cd ' + jobpath + ' && condor_submit condor_'+str(j)+'.jdl'
#		print subcommand
		os.system(subcommand)

